
import { Service, Product, Staff, Expense, Customer, DiscountCode, ShopSettings, Language } from './types';

export const CURRENCY_OPTIONS = [
  { label: 'US Dollar ($)', symbol: '$' },
  { label: 'Euro (€)', symbol: '€' },
  { label: 'British Pound (£)', symbol: '£' },
  { label: 'Pakistani Rupee (Rs.)', symbol: 'Rs.' },
  { label: 'Indian Rupee (₹)', symbol: '₹' },
  { label: 'UAE Dirham (د.إ)', symbol: 'د.إ' },
  { label: 'Saudi Riyal (ر.س)', symbol: 'ر.س' },
  { label: 'Canadian Dollar (C$)', symbol: 'C$' },
  { label: 'Australian Dollar (A$)', symbol: 'A$' },
];

export const COUNTRY_CODES = [
  { code: '+1', country: 'USA/Canada', flag: '🇺🇸' },
  { code: '+44', country: 'UK', flag: '🇬🇧' },
  { code: '+92', country: 'Pakistan', flag: '🇵🇰' },
  { code: '+91', country: 'India', flag: '🇮🇳' },
  { code: '+971', country: 'UAE', flag: '🇦🇪' },
  { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦' },
  { code: '+98', country: 'Iran', flag: '🇮🇷' },
  { code: '+33', country: 'France', flag: '🇫🇷' },
  { code: '+49', country: 'Germany', flag: '🇩🇪' },
  { code: '+39', country: 'Italy', flag: '🇮🇹' },
  { code: '+34', country: 'Spain', flag: '🇪🇸' },
  { code: '+61', country: 'Australia', flag: '🇦🇺' },
  { code: '+86', country: 'China', flag: '🇨🇳' },
  { code: '+81', country: 'Japan', flag: '🇯🇵' },
  { code: '+55', country: 'Brazil', flag: '🇧🇷' },
  { code: '+52', country: 'Mexico', flag: '🇲🇽' },
  { code: '+7', country: 'Russia', flag: '🇷🇺' },
  { code: '+90', country: 'Turkey', flag: '🇹🇷' },
  { code: '+20', country: 'Egypt', flag: '🇪🇬' }
];

export const INITIAL_DISCOUNT_CODES: DiscountCode[] = [
  { code: 'WELCOME10', type: 'percentage', value: 10, description: '10% off for new customers' },
  { code: 'VIP20', type: 'percentage', value: 20, description: '20% off for VIP members' },
  { code: 'SAVE5', type: 'fixed', value: 5, description: '$5 off total' },
];

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: 'TrimTime',
  location: '',
  currency: '$',
  language: 'en',
  defaultCountryCode: '+1',
  whatsappEnabled: true,
  whatsappNumber: '',
  receiptFooter: 'Thank you for choosing us!',
  taxRate: 8,
  taxType: 'excluded',
  billingCycleDay: 1,
  promoCodes: INITIAL_DISCOUNT_CODES,
};

export const TRANSLATIONS = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    pos: 'POS Terminal',
    catalog: 'Catalog',
    customers: 'Customers',
    staff: 'Staff Management',
    finance: 'Finances',
    settings: 'Settings',
    logout: 'Logout',
    shopStatus: 'Shop Status',
    terminalLive: 'Terminal Live',
    
    // Dashboard
    performanceInsights: 'Performance Insights',
    welcomeBack: "Welcome back! Here's what's happening in your shop.",
    revenue: 'Revenue',
    expenses: 'Expenses',
    netProfit: 'Net Profit',
    avgTicket: 'Avg Ticket',
    revenueTrends: 'Revenue Trends',
    recentTransactions: 'Recent Transactions',
    waitingForSale: 'Waiting for first sale...',
    last7Days: 'Last 7 Days',
    lowStockAlerts: 'Low Stock Alerts',
    itemsRestock: 'items need restocking',
    restockNow: 'Restock Now',

    // POS
    services: 'Services',
    products: 'Products',
    searchCatalog: 'Search catalog...',
    scanBarcode: 'Scan Barcode',
    stopScanning: 'Stop Scanning',
    cart: 'Cart',
    emptyCart: 'Empty Cart',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    cash: 'Cash',
    card: 'Card',
    wallet: 'Wallet',
    holdBill: 'Hold Bill',
    heldBills: 'Held Bills',
    resume: 'Resume',
    saleSuccess: 'Sale Success',
    orderCompleted: 'Order completed.',
    shareReceipt: 'Share Receipt',
    downloadPdf: 'Download PDF',
    startNewBill: 'Start New Bill',
    chooseProfessional: 'Choose Professional...',
    walkInClient: 'Walk-in Client',
    quickAddClient: 'Quick Add Client',
    addSelectClient: 'Add & Select Client',
    name: 'Name',
    mobile: 'Mobile',
    email: 'Email',
    optional: 'Optional',
    whatsAppReceipt: 'WhatsApp Receipt',
    retail: 'Retail',
    items: 'Items',
    viewCart: 'View Cart',
    held: 'Held',
    selectToResume: 'Select to resume',
    saveSelect: 'Save & Select',
    scanner: 'Scanner',
    alignBarcode: 'Align barcode horizontally',
    unknownProduct: 'Unknown Product',
    itemNotCatalog: 'Item not in catalog. Try manual search.',
    cameraPermission: 'Camera Permission Denied',
    cameraError: 'Camera Error',
    added: 'Added',
    fillOrder: 'Please add items and assign a professional.',
    discardBill: 'Discard this held bill?',
    amountReceived: 'Amount Received',
    change: 'Change',
    confirmPayment: 'Confirm Payment',
    cancel: 'Cancel',

    // Finance
    shopPerformance: 'Shop Performance',
    commissionReport: 'Commission Report',
    payrollReport: 'Generate payroll reports by date range.',
    newExpense: 'New Expense',
    history: 'History',
    periodRevenue: 'Period Revenue',
    totalPayout: 'Total Payout',
    professional: 'Professional',
    salesCount: 'Sales Count',
    totalSales: 'Total Sales',
    payout: 'Payout',
    rate: 'Rate',
    category: 'Category',
    amount: 'Amount',
    details: 'Details',
    addExpense: 'Add Expense',
    smartInsights: 'Smart AI Insights',
    generateAdvice: 'Generate Advice',
    analyzing: 'Analyzing...',
    aiPrompt: 'Tap "Generate Advice" for a personalized business analysis.',
    noSalesPeriod: 'No sales found in this period.',
    noRecords: 'No records found.',
    noteDetails: 'Note down any details...',
    exportReports: 'Export Reports',
    downloadDaily: 'Download Daily',
    downloadWeekly: 'Download Weekly',
    downloadMonthly: 'Download Monthly',

    // Customers
    directory: 'Directory',
    clientProfiles: 'Client profiles and history.',
    addClient: 'Add Client',
    searchClients: 'Search clients...',
    visits: 'Visits',
    lifetime: 'Lifetime',
    lastSeen: 'Last Seen',
    stylePreferences: 'Style Preferences',
    noNotes: 'No notes on file.',
    date: 'Date',
    itemsList: 'Items', // Renamed to avoid collision with generic 'items'
    registerClient: 'Register Client',
    createProfile: 'Create Profile',
    pickClient: 'Pick a client to review their grooming history.',
    member: 'Member',
    vip: 'VIP',

    // Staff
    teamHub: 'Team Hub',
    manageAccess: 'Manage access and earnings.',
    addStaff: 'Add Staff',
    loginId: 'Login ID',
    role: 'Role',
    commission: 'Commission',
    actions: 'Actions',
    editProfessional: 'Edit Professional',
    addToTeam: 'Add to Team',
    fullName: 'Full Name',
    username: 'Username',
    password: 'Password',
    employee: 'Employee',
    admin: 'Admin',
    saveProfessional: 'Save Professional',
    updateProfessional: 'Update Professional',

    // Inventory
    shopCatalog: 'Shop Catalog',
    updatePrices: 'Update prices and stock.',
    newService: 'New Service',
    newProduct: 'New Product',
    inventory: 'Inventory',
    itemDetails: 'Item Details',
    stockStatus: 'Stock Status',
    price: 'Price',
    editEntry: 'Edit Entry',
    newEntry: 'New Entry',
    labelName: 'Label Name',
    barcode: 'Barcode',
    mins: 'Mins',
    cost: 'Cost',
    initialStock: 'Initial Stock',
    saveChanges: 'Save Changes',
    unitsLeft: 'Units left',
    session: 'session',
    alertQty: 'Alert Qty',

    // Settings
    fineTune: 'Fine-tune your shop and communications.',
    shopBranding: 'Shop Branding & Localization',
    terminalIdentity: 'Terminal Identity',
    language: 'Language',
    preferredCurrency: 'Preferred Currency',
    defaultCountryCode: 'Default Country Code',
    taxCalculation: 'Tax Calculation',
    taxRate: 'Tax Rate (%)',
    receiptFooter: 'Receipt Footer',
    whatsAppSummaries: 'WhatsApp Summaries',
    enableWhatsApp: 'Enable digital receipts via WhatsApp.',
    businessMobile: 'Business Mobile Number',
    resetChanges: 'Reset Changes',
    saveSettings: 'Save All Settings',
    excluded: 'Excluded',
    included: 'Included',
    customSymbol: 'Custom symbol...',
    billingCycle: 'Billing Cycle',
    billingDay: 'Start Day of Month',
    dangerZone: 'Danger Zone',
    resetSales: 'Reset Sales History',
    resetSalesDesc: 'Permanently delete all sales history. This cannot be undone.',
    confirmReset: 'Are you sure you want to delete all sales history?',
    promoCodes: 'Promo Codes & Coupons',
    addPromo: 'Add Promo Code',
    code: 'Code',
    discountType: 'Discount Type',
    value: 'Value',
    description: 'Description',
    fixed: 'Fixed Amount',
    percentage: 'Percentage (%)',

    // Login
    premiumAccess: 'Premium Terminal Access',
    securityKey: 'Security Key',
    enterDashboard: 'Enter Dashboard',
    authorizedUse: 'Authorized Use Only',
    contactAdmin: 'Contact System Admin',
    invalidLogin: 'Invalid username or password',
    stayLoggedIn: 'Stay logged in for 30 days',
  },
  ur: {
    // ... existing Urdu translations ...
    // Added for country code
    defaultCountryCode: 'پہلے سے طے شدہ ملک کا کوڈ',
    // ... existing ...
    // Navigation
    dashboard: 'ڈیش بورڈ',
    pos: 'پوائنٹ آف سیل',
    catalog: 'کیٹلاگ',
    customers: 'صارفین',
    staff: 'عملہ',
    finance: 'مالیات',
    settings: 'ترتیبات',
    logout: 'لاگ آؤٹ',
    shopStatus: 'دکان کی حیثیت',
    terminalLive: 'ٹرمینل لائیو',

    // Dashboard
    performanceInsights: 'کارکردگی کی بصیرت',
    welcomeBack: "خوش آمدید! یہاں آپ کی دکان کی صورتحال ہے۔",
    revenue: 'آمدنی',
    expenses: 'اخراجات',
    netProfit: 'خالص منافع',
    avgTicket: 'اوسط ٹکٹ',
    revenueTrends: 'آمدنی کا رجحان',
    recentTransactions: 'حالیہ لین دین',
    waitingForSale: 'پہلی فروخت کا انتظار...',
    last7Days: 'پچھلے 7 دن',
    lowStockAlerts: 'کم اسٹاک انتباہات',
    itemsRestock: 'اشیاء کو دوبارہ ذخیرہ کرنے کی ضرورت ہے',
    restockNow: 'ابھی ریسٹاک کریں',

    // POS
    services: 'خدمات',
    products: 'مصنوعات',
    searchCatalog: 'کیٹلاگ تلاش کریں...',
    scanBarcode: 'بارکوڈ اسکین کریں',
    stopScanning: 'اسکیننگ روکیں',
    cart: 'ٹوکری',
    emptyCart: 'خالی ٹوکری',
    subtotal: 'ذیلی کل',
    discount: 'رعایت',
    tax: 'ٹیکس',
    total: 'کل',
    cash: 'نقد',
    card: 'کارڈ',
    wallet: 'والٹ',
    holdBill: 'بل ہولڈ کریں',
    heldBills: 'ہولڈ شدہ بل',
    resume: 'دوبارہ شروع کریں',
    saleSuccess: 'فروخت کامیاب',
    orderCompleted: 'آرڈر مکمل ہو گیا۔',
    shareReceipt: 'رسید شیئر کریں',
    downloadPdf: 'PDF ڈاؤن لوڈ کریں',
    startNewBill: 'نیا بل شروع کریں',
    chooseProfessional: 'پیشہ ور کا انتخاب کریں...',
    walkInClient: 'واک ان کلائنٹ',
    quickAddClient: 'فوری کلائنٹ شامل کریں',
    addSelectClient: 'شامل کریں اور منتخب کریں',
    name: 'نام',
    mobile: 'موبائل',
    email: 'ای میل',
    optional: 'اختیاری',
    whatsAppReceipt: 'واٹس ایپ رسید',
    retail: 'ریٹیل',
    items: 'اشیاء',
    viewCart: 'کارٹ دیکھیں',
    held: 'ہولڈ',
    selectToResume: 'دوبارہ شروع کرنے کے لیے منتخب کریں',
    saveSelect: 'محفوظ کریں اور منتخب کریں',
    scanner: 'اسکینر',
    alignBarcode: 'بارکوڈ کو افقی سیدھ میں رکھیں',
    unknownProduct: 'نامعلوم مصنوعات',
    itemNotCatalog: 'آئٹم کیٹلاگ میں نہیں ہے۔ دستی تلاش کریں۔',
    cameraPermission: 'کیمرے کی اجازت نہیں',
    cameraError: 'کیمرے کی خرابی',
    added: 'شامل کیا گیا',
    fillOrder: 'براہ کرم اشیاء شامل کریں اور عملہ منتخب کریں۔',
    discardBill: 'کیا اس ہولڈ شدہ بل کو ختم کریں؟',
    amountReceived: 'وصول شدہ رقم',
    change: 'بقایا',
    confirmPayment: 'ادائیگی کی تصدیق کریں',
    cancel: 'منسوخ کریں',

    // Finance
    shopPerformance: 'دکان کی کارکردگی',
    commissionReport: 'کمیشن رپورٹ',
    payrollReport: 'تاریخ کی حد کے مطابق پے رول رپورٹس تیار کریں۔',
    newExpense: 'نیا خرچ',
    history: 'تاریخچہ',
    periodRevenue: 'مدت کی آمدنی',
    totalPayout: 'کل ادائیگی',
    professional: 'پیشہ ور',
    salesCount: 'فروخت کی تعداد',
    totalSales: 'کل فروخت',
    payout: 'ادائیگی',
    rate: 'شرح',
    category: 'زمرہ',
    amount: 'رقم',
    details: 'تفصیلات',
    addExpense: 'خرچ شامل کریں',
    smartInsights: 'اسمارٹ AI بصیرت',
    generateAdvice: 'مشورہ حاصل کریں',
    analyzing: 'تجزیہ کیا جا رہا ہے...',
    aiPrompt: 'ذاتی کاروباری تجزیہ کے لیے "مشورہ حاصل کریں" پر ٹیپ کریں۔',
    noSalesPeriod: 'اس مدت میں کوئی فروخت نہیں ملی۔',
    noRecords: 'کوئی ریکارڈ نہیں ملا۔',
    noteDetails: 'تفصیلات نوٹ کریں...',
    exportReports: 'رپورٹس برآمد کریں',
    downloadDaily: 'روزانہ ڈاؤن لوڈ کریں',
    downloadWeekly: 'ہفتہ وار ڈاؤن لوڈ کریں',
    downloadMonthly: 'ماہانہ ڈاؤن لوڈ کریں',

    // Customers
    directory: 'ڈائریکٹری',
    clientProfiles: 'کلائنٹ پروفائلز اور تاریخ۔',
    addClient: 'کلائنٹ شامل کریں',
    searchClients: 'کلائنٹ تلاش کریں...',
    visits: 'دورے',
    lifetime: 'لائف ٹائم',
    lastSeen: 'آخری بار دیکھا گیا',
    stylePreferences: 'اسٹائل کی ترجیحات',
    noNotes: 'کوئی نوٹ موجود نہیں۔',
    date: 'تاریخ',
    itemsList: 'اشیاء',
    registerClient: 'کلائنٹ رجسٹر کریں',
    createProfile: 'پروفائل بنائیں',
    pickClient: 'گرومنگ کی تاریخ کا جائزہ لینے کے لیے کلائنٹ کا انتخاب کریں۔',
    member: 'رکن',
    vip: 'VIP',

    // Staff
    teamHub: 'ٹیم ہب',
    manageAccess: 'رسائی اور کمائی کا انتظام کریں۔',
    addStaff: 'عملہ شامل کریں',
    loginId: 'لاگ ان آئی ڈی',
    role: 'کردار',
    commission: 'کمیشن',
    actions: 'ایڪشن',
    editProfessional: 'پیشہ ور میں ترمیم کریں',
    addToTeam: 'ٹیم میں شامل کریں',
    fullName: 'پورا نام',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    employee: 'ملازم',
    admin: 'ایڈمن',
    saveProfessional: 'پیشہ ور محفوظ کریں',
    updateProfessional: 'پیشہ ور کو اپ ڈیٹ کریں',

    // Inventory
    shopCatalog: 'دکان کیٹلاگ',
    updatePrices: 'قیمتیں اور اسٹاک اپ ڈیٹ کریں۔',
    newService: 'نئی سروس',
    newProduct: 'نئی پروڈکٹ',
    inventory: 'انوینٹری',
    itemDetails: 'آئٹم کی تفصیلات',
    stockStatus: 'اسٹاک کی حیثیت',
    price: 'قیمت',
    editEntry: 'اندراج میں ترمیم کریں',
    newEntry: 'نئی اندراج',
    labelName: 'لیبل کا نام',
    barcode: 'بار کوڈ',
    mins: 'منٹ',
    cost: 'لاگت',
    initialStock: 'ابتدائی اسٹاک',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    unitsLeft: 'یونٹس باقی',
    session: 'سیشن',
    alertQty: 'انتباہ کی مقدار',

    // Settings
    fineTune: 'اپنی دکان اور مواصلات کو ٹھیک کریں۔',
    shopBranding: 'دکان کی برانڈنگ',
    terminalIdentity: 'ٹرمینل شناخت',
    language: 'زبان',
    preferredCurrency: 'پسندیدہ کرنسی',
    taxCalculation: 'ٹیکس کا حساب کتاب',
    taxRate: 'ٹیکس کی شرح (%)',
    receiptFooter: 'رسید کا فوٹر',
    whatsAppSummaries: 'واٹس ایپ خلاصے',
    enableWhatsApp: 'واٹس ایپ کے ذریعے ڈیجیٹل رسیدیں فعال کریں۔',
    businessMobile: 'کاروباری موبائل نمبر',
    resetChanges: 'تبدیلیاں ری سیٹ کریں',
    saveSettings: 'تمام ترتیبات محفوظ کریں',
    excluded: 'شامل نہیں',
    included: 'شامل',
    customSymbol: 'حسب ضرورت علامت...',
    billingCycle: 'بلنگ سائیکل',
    billingDay: 'مہینے کا آغاز دن',
    dangerZone: 'خطرہ زون',
    resetSales: 'فروخت کی تاریخ ری سیٹ کریں',
    resetSalesDesc: 'تمام فروخت کی تاریخ کو مستقل طور پر حذف کریں۔ یہ عمل واپس نہیں کیا جا سکتا۔',
    confirmReset: 'کیا آپ واقعی فروخت کے تمام ریکارڈ حذف کرنا چاہتے ہیں؟',
    promoCodes: 'پرومو کوڈز اور کوپن',
    addPromo: 'پرومو کوڈ شامل کریں',
    code: 'کوڈ',
    discountType: 'ڈسکاؤنٹ کی قسم',
    value: 'قیمت',
    description: 'تفصیل',
    fixed: 'مقررہ رقم',
    percentage: 'فیصد (%)',

    // Login
    premiumAccess: 'پریمیم ٹرمینل تک رسائی',
    securityKey: 'سیکیورٹی کلید',
    enterDashboard: 'ڈیش بورڈ میں داخل ہوں',
    authorizedUse: 'صرف مجاز استعمال',
    contactAdmin: 'سسٹم ایڈمن سے رابطہ کریں',
    invalidLogin: 'غلط صارف نام یا پاس ورڈ',
    stayLoggedIn: '30 دن تک لاگ ان رہیں',
  },
  fa: {
    // ... existing Persian translations ...
    defaultCountryCode: 'کد کشور پیش‌فرض',
    // ... existing ...
    // Navigation
    dashboard: 'داشبورد',
    pos: 'پایانه فروش',
    catalog: 'فهرست خدمات',
    customers: 'مشتریان',
    staff: 'مدیریت کارکنان',
    finance: 'امور مالی',
    settings: 'تنظیمات',
    logout: 'خروج',
    shopStatus: 'وضعیت فروشگاه',
    terminalLive: 'ترمینال فعال',

    // Dashboard
    performanceInsights: 'بینش عملکرد',
    welcomeBack: 'خوش آمدید! نگاهی به وضعیت فروشگاه شما.',
    revenue: 'درآمد',
    expenses: 'هزینه‌ها',
    netProfit: 'سود خالص',
    avgTicket: 'میانگین سفارش',
    revenueTrends: 'روند درآمد',
    recentTransactions: 'تراکنش‌های اخیر',
    waitingForSale: 'منتظر اولین فروش...',
    last7Days: '۷ روز گذشته',
    lowStockAlerts: 'هشدارهای موجودی کم',
    itemsRestock: 'اقلام نیاز به شارژ مجدد دارند',
    restockNow: 'شارژ مجدد',

    // POS
    services: 'خدمات',
    products: 'محصولات',
    searchCatalog: 'جستجوی فهرست...',
    scanBarcode: 'اسکن بارکد',
    stopScanning: 'توقف اسکن',
    cart: 'سبد خرید',
    emptyCart: 'سبد خالی',
    subtotal: 'جمع جزء',
    discount: 'تخفیف',
    tax: 'مالیات',
    total: 'مجموع',
    cash: 'نقد',
    card: 'کارت',
    wallet: 'کیف پول',
    holdBill: 'تعلیق فاکتور',
    heldBills: 'فاکتورهای معلق',
    resume: 'ادامه',
    saleSuccess: 'فروش موفق',
    orderCompleted: 'سفارش تکمیل شد.',
    shareReceipt: 'اشتراک رسید',
    downloadPdf: 'دانلود PDF',
    startNewBill: 'شروع فاکتور جدید',
    chooseProfessional: 'انتخاب متخصص...',
    walkInClient: 'مشتری حضوری',
    quickAddClient: 'افزودن سریع مشتری',
    addSelectClient: 'افزودن و انتخاب',
    name: 'نام',
    mobile: 'موبایل',
    email: 'ایمیل',
    optional: 'اختیاری',
    whatsAppReceipt: 'رسید واتساپ',
    retail: 'خرده فروشی',
    items: 'اقلام',
    viewCart: 'مشاهده سبد',
    held: 'نگه داشته شده',
    selectToResume: 'برای ادامه انتخاب کنید',
    saveSelect: 'ذخیره و انتخاب',
    scanner: 'اسکنر',
    alignBarcode: 'بارکد را به صورت افقی تراز کنید',
    unknownProduct: 'محصول ناشناخته',
    itemNotCatalog: 'کالا در فهرست نیست. جستجوی دستی کنید.',
    cameraPermission: 'مجوز دوربین رد شد',
    cameraError: 'خطای دوربین',
    added: 'اضافه شد',
    fillOrder: 'لطفاً اقلام را اضافه کنید و یک متخصص تعیین کنید.',
    discardBill: 'این صورتحساب نگه داشته شده را دور بریزید؟',
    amountReceived: 'مبلغ دریافتی',
    change: 'باقی‌مانده',
    confirmPayment: 'تایید پرداخت',
    cancel: 'لغو',

    // Finance
    shopPerformance: 'عملکرد فروشگاه',
    commissionReport: 'گزارش کمیسیون',
    payrollReport: 'ایجاد گزارش حقوق و دستمزد بر اساس تاریخ.',
    newExpense: 'هزینه جدید',
    history: 'تاریخچه',
    periodRevenue: 'درآمد دوره',
    totalPayout: 'مجموع پرداختی',
    professional: 'متخصص',
    salesCount: 'تعداد فروش',
    totalSales: 'مجموع فروش',
    payout: 'پرداختی',
    rate: 'نرخ',
    category: 'دسته',
    amount: 'مبلغ',
    details: 'جزئیات',
    addExpense: 'افزودن هزینه',
    smartInsights: 'هوش مصنوعی',
    generateAdvice: 'تولید مشاوره',
    analyzing: 'در حال تحلیل...',
    aiPrompt: 'برای تحلیل کسب و کار روی "تولید مشاوره" ضربه بزنید.',
    noSalesPeriod: 'فروشی در این دوره یافت نشد.',
    noRecords: 'رکوردی یافت نشد.',
    noteDetails: 'یادداشت جزئیات...',
    exportReports: 'صدور گزارشات',
    downloadDaily: 'دانلود روزانه',
    downloadWeekly: 'دانلود هفتگی',
    downloadMonthly: 'دانلود ماهانه',

    // Customers
    directory: 'دفترچه',
    clientProfiles: 'پروفایل و تاریخچه مشتریان.',
    addClient: 'افزودن مشتری',
    searchClients: 'جستجوی مشتری...',
    visits: 'بازدیدها',
    lifetime: 'مادام‌العمر',
    lastSeen: 'آخرین بازدید',
    stylePreferences: 'ترجیحات استایل',
    noNotes: 'یادداشتی موجود نیست.',
    date: 'تاریخ',
    itemsList: 'اقلام',
    registerClient: 'ثبت مشتری',
    createProfile: 'ایجاد پروفایل',
    pickClient: 'مشتری را برای بررسی تاریخچه انتخاب کنید.',
    member: 'عضو',
    vip: 'ویژه',

    // Staff
    teamHub: 'تیم ما',
    manageAccess: 'مدیریت دسترسی و درآمد.',
    addStaff: 'افزودن پرسنل',
    loginId: 'شناسه ورود',
    role: 'نقش',
    commission: 'کمیسیون',
    actions: 'عملیات',
    editProfessional: 'ویرایش متخصص',
    addToTeam: 'افزودن به تیم',
    fullName: 'نام کامل',
    username: 'نام کاربری',
    password: 'رمز عبور',
    employee: 'کارمند',
    admin: 'مدیر',
    saveProfessional: 'ذخیره متخصص',
    updateProfessional: 'بروزرسانی متخصص',

    // Inventory
    shopCatalog: 'فهرست فروشگاه',
    updatePrices: 'بروزرسانی قیمت و موجودی.',
    newService: 'خدمت جدید',
    newProduct: 'محصول جدید',
    inventory: 'انبار',
    itemDetails: 'جزئیات آیتم',
    stockStatus: 'وضعیت موجودی',
    price: 'قیمت',
    editEntry: 'ویرایش ورودی',
    newEntry: 'ورودی جدید',
    labelName: 'نام برچسب',
    barcode: 'بارکد',
    mins: 'دقیقه',
    cost: 'هزینه',
    initialStock: 'موجودی اولیه',
    saveChanges: 'ذخیره تغییرات',
    unitsLeft: 'عدد باقی‌مانده',
    session: 'جلسه',
    alertQty: 'هشدار تعداد',

    // Settings
    fineTune: 'تنظیمات فروشگاه و ارتباطات.',
    shopBranding: 'برندینگ و بومی‌سازی',
    terminalIdentity: 'هویت ترمینال',
    language: 'زبان',
    preferredCurrency: 'ارز ترجیحی',
    taxCalculation: 'محاسبه مالیات',
    taxRate: 'نرخ مالیات (%)',
    receiptFooter: 'پاورقی رسید',
    whatsAppSummaries: 'خلاصه واتساپ',
    enableWhatsApp: 'فعالسازی رسید دیجیتال در واتساپ.',
    businessMobile: 'شماره موبایل تجاری',
    resetChanges: 'بازنشانی تغییرات',
    saveSettings: 'ذخیره تنظیمات',
    excluded: 'مستثنی',
    included: 'شامل',
    customSymbol: 'نماد سفارشی...',
    billingCycle: 'چرخه صورتحساب',
    billingDay: 'روز شروع ماه',
    dangerZone: 'منطقه خطر',
    resetSales: 'بازنشانی تاریخچه فروش',
    resetSalesDesc: 'حذف دائمی تمام سوابق فروش. این عمل قابل بازگشت نیست.',
    confirmReset: 'آیا مطمئن هستید که می‌خواهید تمام سوابق فروش را حذف کنید؟',
    promoCodes: 'کدهای تخفیف و کوپن',
    addPromo: 'افزودن کد تخفیف',
    code: 'کد',
    discountType: 'نوع تخفیف',
    value: 'مقدار',
    description: 'توضیحات',
    fixed: 'مبلغ ثابت',
    percentage: 'درصد (%)',

    // Login
    premiumAccess: 'دسترسی ترمینال ویژه',
    securityKey: 'کلید امنیتی',
    enterDashboard: 'ورود به داشبورد',
    authorizedUse: 'فقط استفاده مجاز',
    contactAdmin: 'تماس با مدیر سیستم',
    invalidLogin: 'نام کاربری یا رمز عبور نامعتبر',
    stayLoggedIn: 'برای ۳۰ روز وارد بمانید',
  },
  hi: {
    // ... existing Hindi translations ...
    defaultCountryCode: 'डिफ़ॉल्ट देश कोड',
    // ... existing ...
    // Navigation
    dashboard: 'डैशबोर्ड',
    pos: 'पीओएस टर्मिनल',
    catalog: 'कैटलॉग',
    customers: 'ग्राहक',
    staff: 'कर्मचारी प्रबंधन',
    finance: 'वित्त',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    shopStatus: 'दुकान की स्थिति',
    terminalLive: 'टर्मिनल लाइव',

    // Dashboard
    performanceInsights: 'प्रदर्शन जानकारी',
    welcomeBack: "वापसी पर स्वागत है! यहाँ आपकी दुकान में क्या हो रहा है।",
    revenue: 'राजस्व',
    expenses: 'खर्चे',
    netProfit: 'शुद्ध लाभ',
    avgTicket: 'औसत टिकट',
    revenueTrends: 'राजस्व रुझान',
    recentTransactions: 'हाल ही के लेनदेन',
    waitingForSale: 'पहली बिक्री का इंतजार...',
    last7Days: 'पिछले 7 दिन',
    lowStockAlerts: 'कम स्टॉक अलर्ट',
    itemsRestock: 'सामान को फिर से भरने की जरूरत है',
    restockNow: 'अभी भरें',

    // POS
    services: 'सेवाएं',
    products: 'उत्पाद',
    searchCatalog: 'कैटलॉग खोजें...',
    scanBarcode: 'बारकोड स्कैन करें',
    stopScanning: 'स्कैनिंग रोकें',
    cart: 'कार्ट',
    emptyCart: 'खाली कार्ट',
    subtotal: 'उप-योग',
    discount: 'छूट',
    tax: 'कर',
    total: 'कुल',
    cash: 'नकद',
    card: 'कार्ड',
    wallet: 'वॉलेट',
    holdBill: 'बिल होल्ड करें',
    heldBills: 'होल्ड किए गए बिल',
    resume: 'फिर से शुरू करें',
    saleSuccess: 'बिक्री सफल',
    orderCompleted: 'ऑर्डर पूरा हुआ।',
    shareReceipt: 'रसीद शेयर करें',
    downloadPdf: 'PDF डाउनलोड करें',
    startNewBill: 'नया बिल शुरू करें',
    chooseProfessional: 'प्रोफेशनल चुनें...',
    walkInClient: 'वॉक-इन ग्राहक',
    quickAddClient: 'ग्राहक जल्दी जोड़ें',
    addSelectClient: 'जोड़ें और चुनें',
    name: 'नाम',
    mobile: 'मोबाइल',
    email: 'ईमेल',
    optional: 'वैकल्पिक',
    whatsAppReceipt: 'व्हाट्सएप रसीद',
    retail: 'खुदरा',
    items: 'सामान',
    viewCart: 'कार्ट देखें',
    held: 'होल्ड',
    selectToResume: 'फिर से शुरू करने के लिए चुनें',
    saveSelect: 'सहेजें और चुनें',
    scanner: 'स्कैनर',
    alignBarcode: 'بارकोड को क्षैतिज रूप से संरेखित करें',
    unknownProduct: 'अज्ञात उत्पाद',
    itemNotCatalog: 'आइटम कैटलॉग में नहीं है। मैन्युअल खोज करें।',
    cameraPermission: 'कैमरा अनुमति अस्वीकार',
    cameraError: 'कैमरा त्रुटि',
    added: 'जोड़ा गया',
    fillOrder: 'कृपया सामान जोड़ें और एक पेशेवर चुनें।',
    discardBill: 'क्या इस होल्ड बिल को हटा दें?',
    amountReceived: 'प्राप्त राशि',
    change: 'छुट्टा',
    confirmPayment: 'भुगतान की पुष्टि करें',
    cancel: 'रद्द करें',

    // Finance
    shopPerformance: 'दुकान का प्रदर्शन',
    commissionReport: 'कमीशन रिपोर्ट',
    payrollReport: 'वेतन रिपोर्ट',
    newExpense: 'नया खर्च',
    history: 'इतिहास',
    periodRevenue: 'अवधि राजस्व',
    totalPayout: 'कुल भुगतान',
    professional: 'प्रोफेशनल',
    salesCount: 'बिक्री संख्या',
    totalSales: 'कुल बिक्री',
    payout: 'भुगतान',
    rate: 'दर',
    category: 'श्रेणी',
    amount: 'राशि',
    details: 'विवरण',
    addExpense: 'खर्च जोड़ें',
    smartInsights: 'स्मार्ट एआई अंतर्दृष्टि',
    generateAdvice: 'सलाह उत्पन्न करें',
    analyzing: 'विश्लेषण कर रहा है...',
    aiPrompt: 'निजीकृत व्यवसाय विश्लेषण के लिए "सलाह उत्पन्न करें" पर टैप करें।',
    noSalesPeriod: 'इस अवधि में कोई बिक्री नहीं मिली।',
    noRecords: 'कोई रिकॉर्ड नहीं मिला।',
    noteDetails: 'विवरण नोट करें...',
    exportReports: 'रिपोर्ट निर्यात करें',
    downloadDaily: 'दैनिक डाउनलोड करें',
    downloadWeekly: 'साप्ताहिक डाउनलोड करें',
    downloadMonthly: 'मासिक डाउनलोड करें',

    // Customers
    directory: 'निर्देशिका',
    clientProfiles: 'ग्राहक प्रोफाइल और इतिहास।',
    addClient: 'ग्राहक जोड़ें',
    searchClients: 'ग्राहक खोजें...',
    visits: 'विज़िट',
    lifetime: 'जीवनकाल',
    lastSeen: 'अंतिम बार देखा गया',
    stylePreferences: 'स्टाइल प्राथमिकताएं',
    noNotes: 'कोई नोट नहीं।',
    date: 'तारीख',
    itemsList: 'सामान',
    registerClient: 'ग्राहक पंजीकृत करें',
    createProfile: 'प्रोफाइल बनाएं',
    pickClient: 'इतिहास देखने के लिए ग्राहक चुनें।',
    member: 'सदस्य',
    vip: 'वीआईपी',

    // Staff
    teamHub: 'टीम हब',
    manageAccess: 'एक्सेस और कमाई प्रबंधित करें।',
    addStaff: 'स्टाफ जोड़ें',
    loginId: 'लॉगिन आईडी',
    role: 'भूमिका',
    commission: 'कमीशन',
    actions: 'कार्रवाई',
    editProfessional: 'प्रोफेशनल संपादित करें',
    addToTeam: 'टीम में शामिल करें',
    fullName: 'पूरा नाम',
    username: 'उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    employee: 'कर्मचारी',
    admin: 'एडमिन',
    saveProfessional: 'प्रोफेशनल सहेजें',
    updateProfessional: 'प्रोफेशनल अपडेट करें',

    // Inventory
    shopCatalog: 'दुकान कैटलॉग',
    updatePrices: 'कीमतें और स्टॉक अपडेट करें।',
    newService: 'नई सेवा',
    newProduct: 'नया उत्पाद',
    inventory: 'इन्वेंटरी',
    itemDetails: 'सामान विवरण',
    stockStatus: 'स्टॉक स्थिति',
    price: 'कीमत',
    editEntry: 'प्रविष्टि संपादित करें',
    newEntry: 'नई प्रविष्टि',
    labelName: 'लेबल नाम',
    barcode: 'बारकोड',
    mins: 'मिनट',
    cost: 'लागत',
    initialStock: 'प्रारंभिक स्टॉक',
    saveChanges: 'परिवर्तन सहेजें',
    unitsLeft: 'इकाइयां बची हैं',
    session: 'सत्र',
    alertQty: 'अलर्ट मात्रा',

    // Settings
    fineTune: 'अपनी दुकान और संचार को ठीक करें।',
    shopBranding: 'दुकान ब्रांडिंग',
    terminalIdentity: 'टर्मिनल पहचान',
    language: 'भाषा',
    preferredCurrency: 'पसंदीदा मुद्रा',
    taxCalculation: 'कर गणना',
    taxRate: 'कर दर (%)',
    receiptFooter: 'रसीद पाद लेख',
    whatsAppSummaries: 'व्हाट्सएप सारांश',
    enableWhatsApp: 'व्हाट्सएप के माध्यम से डिजिटल रसीदें सक्षम करें।',
    businessMobile: 'व्यवसाय मोबाइल नंबर',
    resetChanges: 'परिवर्तन रीसेट करें',
    saveSettings: 'सभी सेटिंग्स सहेजें',
    excluded: 'छोड़ा हुआ',
    included: 'शामिल',
    customSymbol: 'कस्टम प्रतीक...',
    billingCycle: 'बिलिंग चक्र',
    billingDay: 'महीने का शुरू दिन',
    dangerZone: 'खतरा क्षेत्र',
    resetSales: 'बिक्री इतिहास रीसेट करें',
    resetSalesDesc: 'सभी बिक्री इतिहास को स्थायी रूप से हटा दें। इसे पूर्ववत नहीं किया जा सकता।',
    confirmReset: 'क्या आप वाकई सभी बिक्री इतिहास को हटाना चाहते हैं?',
    promoCodes: 'प्रोमो कोड और कूपन',
    addPromo: 'प्रोमो कोड जोड़ें',
    code: 'कोड',
    discountType: 'छूट प्रकार',
    value: 'मूल्य',
    description: 'विवरण',
    fixed: 'निश्चित राशि',
    percentage: 'प्रतिशत (%)',

    // Login
    premiumAccess: 'पریمियम टर्मिनल एक्सेस',
    securityKey: 'सुरक्षा कुंजी',
    enterDashboard: 'डैशबोर्ड दर्ज करें',
    authorizedUse: 'केवल अधिकृत उपयोग',
    contactAdmin: 'सिस्टम एडमिन से संपर्क करें',
    invalidLogin: 'अमान्य उपयोगकर्ता नाम या पासवर्ड',
    stayLoggedIn: '30 दिनों तक लॉग इन रहें',
  }
};

export const INITIAL_SERVICES: Service[] = [
  { id: 's1', name: 'Classic Haircut', price: 35, duration: 30, category: 'Hair' },
  { id: 's2', name: 'Skin Fade', price: 45, duration: 45, category: 'Hair' },
  { id: 's3', name: 'Beard Trim', price: 20, duration: 20, category: 'Beard' },
  { id: 's4', name: 'Luxury Shave', price: 50, duration: 60, category: 'Shave' },
  { id: 's5', name: 'Kid\'s Cut', price: 25, duration: 30, category: 'Hair' },
  { id: 's6', name: 'Head Shave', price: 30, duration: 30, category: 'Hair' },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 'p1', name: 'Pomade Matte', price: 18, cost: 8, stock: 24, barcode: '123456789012', lowStockThreshold: 15 },
  { id: 'p2', name: 'Beard Oil', price: 22, cost: 10, stock: 15, barcode: '098765432109', lowStockThreshold: 15 },
  { id: 'p3', name: 'Aftershave Balm', price: 25, cost: 12, stock: 10, barcode: '112233445566', lowStockThreshold: 15 },
  { id: 'p4', name: 'Texture Spray', price: 20, cost: 9, stock: 8, barcode: '665544332211', lowStockThreshold: 15 },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'st1', name: 'Admin User', role: 'admin', commission: 0, username: '1234', password: '1234' },
  { id: 'st2', name: 'Alex Rivers', role: 'employee', commission: 40, username: 'alex', password: 'password123' },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'e1', date: '2024-05-01', category: 'Rent', amount: 2000, description: 'Monthly Shop Rent' },
  { id: 'e2', date: '2024-05-02', category: 'Utilities', amount: 350, description: 'Electricity & Water' },
  { id: 'e3', date: '2024-05-05', category: 'Supplies', amount: 150, description: 'Towels & Cleaning' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'John Smith', phone: '555-0101', email: 'john@example.com', notes: 'Likes a low taper fade.', createdAt: '2024-01-15' },
  { id: 'c2', name: 'Marcus Brown', phone: '555-0102', email: 'marcus@example.com', notes: 'Grows beard long.', createdAt: '2024-02-20' },
];
